# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Make Better Space 4 All
short_title: SPACE4
email: space4@space.co.kr
description: > # this means to ignore newlines until "baseurl:"
  SPACE4는 우리 모두가 보다 좋은 공간을 누릴 수 있기를 꿈꾸는 공간디자인 전문 스튜디오 입니다.
  "모두가 꿈꾸는 공간의 가치, SPACE4가 실현합니다."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://space4for.github.io" # the base hostname & protocol for your site
facebook_username: SPACE4-275414592487427
address: 서울특별시 마포구 잔다리로 39, 로뎀빌딩 704호
phone_number : 02.501.9137
fax_number : 02.501.9138

# Build settings
markdown: kramdown
